src/main/java/sies/jsf/controladores/AccionpermitidaController.java
package sies.jsf.controladores;

import siess1.jpa.entidades.Accionpermitida;
import siess1.jsf.controladores.util.JsfUtil;
import siess1.jsf.controladores.util.PaginationHelper;
import siess1.ejb.fachadas.AccionpermitidaFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("accionpermitidaController")
@SessionScoped
public class AccionpermitidaController implements Serializable {

    private Accionpermitida current;
    private DataModel items = null;
    @EJB
    private siess1.ejb.fachadas.AccionpermitidaFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public AccionpermitidaController() {
    }

    public Accionpermitida getSelected() {
        if (current == null) {
            current = new Accionpermitida();
            selectedItemIndex = -1;
        }
        return current;
    }

    private AccionpermitidaFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(100000) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Accionpermitida) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Accionpermitida();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("resources/Bundle").getString("AccionpermitidaCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Accionpermitida) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("resources/Bundle").getString("AccionpermitidaUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Accionpermitida) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("resources/Bundle").getString("AccionpermitidaDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Accionpermitida getAccionpermitida(java.math.BigDecimal id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Accionpermitida.class)
    public static class AccionpermitidaControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AccionpermitidaController controller = (AccionpermitidaController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "accionpermitidaController");
            return controller.getAccionpermitida(getKey(value));
        }

        java.math.BigDecimal getKey(String value) {
            java.math.BigDecimal key;
            key = new java.math.BigDecimal(value);
            return key;
        }

        String getStringKey(java.math.BigDecimal value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Accionpermitida) {
                Accionpermitida o = (Accionpermitida) object;
                return getStringKey(o.getPkAccionpermitida());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Accionpermitida.class.getName());
            }
        }

    }

}

src/main/webapp/catalogos/accionpermitida/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/catalogos/templateAdmin.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateAccionpermitidaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:outputLabel class="msjObligatorios"
                               value ="#{bundle.msjObligatorios}" /> 
                <p:separator> </p:separator>
            
            <h:form>
                <h:panelGrid columns="3">
                    <h:outputLabel value="#{bundle.CreateAccionpermitidaLabel_codigo}" for="codigo" />
                    <p:inputText id="codigo" value="#{accionpermitidaController.selected.codigo}" 
                                 title="#{bundle.CreateAccionpermitidaTitle_codigo}" 
                                 required="true" requiredMessage="#{bundle.CreateAccionpermitidaRequiredMessage_codigo}"/>
                    
                    <h:outputLabel value="*" class="asterisco"> </h:outputLabel> 
                    
                    <h:outputLabel value="#{bundle.CreateAccionpermitidaLabel_descripcion}" for="descripcion" />
                    <p:inputText id="descripcion" value="#{accionpermitidaController.selected.descripcion}" 
                                 title="#{bundle.CreateAccionpermitidaTitle_descripcion}" required="true"
                                 requiredMessage="#{bundle.CreateAccionpermitidaRequiredMessage_descripcion}"/>
                    <h:outputLabel value="*" class="asterisco"> </h:outputLabel> 
                    
                    <h:outputLabel value="#{bundle.CreateAccionpermitidaLabel_ruta}" for="ruta" />
                    <h:inputText id="ruta" value="#{accionpermitidaController.selected.ruta}" 
                                 title="#{bundle.CreateAccionpermitidaTitle_ruta}" required="true" 
                                 requiredMessage="#{bundle.CreateAccionpermitidaRequiredMessage_ruta}"/>
                    <h:outputLabel value="*" class="asterisco"> </h:outputLabel> 
                    
                    <h:outputLabel value="#{bundle.CreateAccionpermitidaLabel_fkAccionpermitida}" for="fkAccionpermitida" />
                    <h:selectOneMenu id="fkAccionpermitida" value="#{accionpermitidaController.selected.fkAccionpermitida}" 
                                     title="#{bundle.CreateAccionpermitidaTitle_fkAccionpermitida}" >
                        <f:selectItems value="#{accionpermitidaController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="*" class="asterisco"> </h:outputLabel> 
                </h:panelGrid>
                <br />
                <h:commandLink action="#{accionpermitidaController.create}" value="#{bundle.CreateAccionpermitidaSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{accionpermitidaController.prepareList}" value="#{bundle.CreateAccionpermitidaShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateAccionpermitidaIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/catalogos/accionpermitida/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/catalogos/templateAdmin.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditAccionpermitidaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                   <h:outputLabel value="#{bundle.EditAccionpermitidaLabel_codigo}" for="codigo" />
                    <h:inputText id="codigo" value="#{accionpermitidaController.selected.codigo}" title="#{bundle.EditAccionpermitidaTitle_codigo}" required="true" requiredMessage="#{bundle.EditAccionpermitidaRequiredMessage_codigo}"/>
                    <h:outputLabel value="#{bundle.EditAccionpermitidaLabel_descripcion}" for="descripcion" />
                    <h:inputText id="descripcion" value="#{accionpermitidaController.selected.descripcion}" title="#{bundle.EditAccionpermitidaTitle_descripcion}" required="true" requiredMessage="#{bundle.EditAccionpermitidaRequiredMessage_descripcion}"/>
                    <h:outputLabel value="#{bundle.EditAccionpermitidaLabel_ruta}" for="ruta" />
                    <h:inputText id="ruta" value="#{accionpermitidaController.selected.ruta}" title="#{bundle.EditAccionpermitidaTitle_ruta}" required="true" requiredMessage="#{bundle.EditAccionpermitidaRequiredMessage_ruta}"/>
                    <h:outputLabel value="#{bundle.EditAccionpermitidaLabel_fkAccionpermitida}" for="fkAccionpermitida" />
                    <h:selectOneMenu id="fkAccionpermitida" value="#{accionpermitidaController.selected.fkAccionpermitida}" title="#{bundle.EditAccionpermitidaTitle_fkAccionpermitida}" >
                        <f:selectItems value="#{accionpermitidaController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{accionpermitidaController.update}" value="#{bundle.EditAccionpermitidaSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditAccionpermitidaViewLink}"/>
                <br />
                <h:commandLink action="#{accionpermitidaController.prepareList}" value="#{bundle.EditAccionpermitidaShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditAccionpermitidaIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/catalogos/accionpermitida/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/catalogos/templateAdmin.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListAccionpermitidaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListAccionpermitidaEmpty}" rendered="#{accionpermitidaController.items.rowCount == 0}"/>
               <p:dataTable id="accionpermitida" value="#{accionpermitidaController.items}"
                            var="item" paginator="true" rows="5" emptyMessage="#{bundle.noresultadosfiltro}"
                                 paginatorTemplate="{CurrentPageReport}
                                 {FirstPageLink} {PreviousPageLink} {PageLinks}
                                 {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                 rowsPerPageTemplate="5, 10, 15">
                   
                   
                   <f:facet name="{Exporters}">
                            <div style="float: bottom; padding-top: 5px ">
                                <h:commandLink class="a">
                                    <p:graphicImage name="/assets/xls.png" width="24"/>
                                    <p:dataExporter type="xls" target="tblaccionpermitida"
                                                    pageOnly="true" fileName="accionpermitidas"/>
                                </h:commandLink>

                                <h:commandLink class="a">
                                    <p:graphicImage name="/assets/pdf.png" width="24"/>
                                    <p:dataExporter type="pdf" target="tblaccionpermitida"
                                                    pageOnly="true" fileName="accionpermitidas" preProcessor="#{personaController.preProcessPDF}"/>
                                </h:commandLink>

                                <h:commandLink class="a">
                                    <p:graphicImage name="/assets/csv.png" width="24"/>
                                    <p:dataExporter type="csv" target="tblaccionpermitida"
                                                    pageOnly="true" fileName="accionpermitidas"/>
                                </h:commandLink>

                                <h:commandLink class="a">
                                    <p:graphicImage name="/assets/xml.png" width="24"/>
                                    <p:dataExporter type="xml" target="tblaccionpermitida"
                                                    pageOnly="true" fileName="accionpermitidas"/>
                                </h:commandLink>
                            </div>
                        </f:facet>

                        <p:column headerText="#{bundle.ListAccionpermitidaTitle_codigo}">
                            <h:outputText value="#{item.codigo}"/>
                        </p:column>
                        
                        <p:column headerText="#{bundle.ListAccionpermitidaTitle_descripcion}">
                            <h:outputText value="#{item.descripcion}"/>
                        </p:column>
                        
                        <p:column headerText="#{bundle.ListAccionpermitidaTitle_ruta}">
                            <h:outputText value="#{item.ruta}"/>
                        </p:column>
                        
                        <p:column headerText="#{bundle.ListAccionpermitidaTitle_fkAccionpermitida}">
                            <h:outputText value="#{item.fkAccionpermitida}"/>
                        </p:column>
                        
                   <p:column exportable="false">
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink class="link" action="#{accionpermitidaController.prepareView}" value="#{bundle.ListAccionpermitidaViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink class="link"  action="#{accionpermitidaController.prepareEdit}" value="#{bundle.ListAccionpermitidaEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink  class="link"  action="#{accionpermitidaController.destroy}" value="#{bundle.ListAccionpermitidaDestroyLink}"/>
                        </p:column>
                    </p:dataTable>
                
                <h3>Exportar</h3>
                    <h:commandLink class="a">
                        <p:graphicImage name="/assets/xls.png"/>
                        <p:dataExporter type="xls" target="tblaccionpermitida"
                                        fileName="accionpermitidas"
                                        preProcessor="#{personaController.preProcessPDF}"/>
                    </h:commandLink>

                    <h:commandLink class="a">
                        <p:graphicImage name="/assets/pdf.png"/>
                        <p:dataExporter type="pdf" target="tblaccionpermitida"
                                        fileName="accionpermitidas"/>
                    </h:commandLink>

                    <h:commandLink class="a">
                        <p:graphicImage name="/assets/csv.png"/>
                        <p:dataExporter type="csv" target="tblaccionpermitida"
                                        fileName="accionpermitidas"/>
                    </h:commandLink>

                    <h:commandLink class="a">
                        <p:graphicImage name="/assets/xml.png"/>
                        <p:dataExporter type="xml" target="tblaccionpermitida"
                                        fileName="accionpermitidas"/>
                    </h:commandLink>
                
                <br />
                <h:commandLink action="#{accionpermitidaController.prepareCreate}" value="#{bundle.ListAccionpermitidaCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListAccionpermitidaIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/catalogos/accionpermitida/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewAccionpermitidaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewAccionpermitidaLabel_pkAccionpermitida}"/>
                    <h:outputText value="#{accionpermitidaController.selected.pkAccionpermitida}" title="#{bundle.ViewAccionpermitidaTitle_pkAccionpermitida}"/>
                    <h:outputText value="#{bundle.ViewAccionpermitidaLabel_codigo}"/>
                    <h:outputText value="#{accionpermitidaController.selected.codigo}" title="#{bundle.ViewAccionpermitidaTitle_codigo}"/>
                    <h:outputText value="#{bundle.ViewAccionpermitidaLabel_descripcion}"/>
                    <h:outputText value="#{accionpermitidaController.selected.descripcion}" title="#{bundle.ViewAccionpermitidaTitle_descripcion}"/>
                    <h:outputText value="#{bundle.ViewAccionpermitidaLabel_ruta}"/>
                    <h:outputText value="#{accionpermitidaController.selected.ruta}" title="#{bundle.ViewAccionpermitidaTitle_ruta}"/>
                    <h:outputText value="#{bundle.ViewAccionpermitidaLabel_fkAccionpermitida}"/>
                    <h:outputText value="#{accionpermitidaController.selected.fkAccionpermitida}" title="#{bundle.ViewAccionpermitidaTitle_fkAccionpermitida}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{accionpermitidaController.destroyAndView}" value="#{bundle.ViewAccionpermitidaDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewAccionpermitidaEditLink}"/>
                <br />
                <h:commandLink action="#{accionpermitidaController.prepareCreate}" value="#{bundle.ViewAccionpermitidaCreateLink}" />
                <br />
                <h:commandLink action="#{accionpermitidaController.prepareList}" value="#{bundle.ViewAccionpermitidaShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewAccionpermitidaIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>